### ISSUE TITLE
Does silvie support packaging of decompressed resources? 

### ISSUE THREAD

**Issue by scienticat** [othias/silvie#1]
Hi,I am a Chinese player.I am very interested in your silvie project. Silver is a game I played when I was young.But the Steam version does not provide Chinese.So I want to translate into Chinese by myself.
So I want to know，Does silvie support packaging of asset ? like translated eng  THX！

**Comment by othias** [comment]
Hello :)
It currently doesn't. Translating the .ENG (dialog files) in itself isn't difficult, but you will have to create a custom spritesheet for the chinese font as the default one doesn't have chinese characters. It can probably be done though, if you can provide a chinese character spritesheet where the glyphs are about the same size as the default ones

**Comment by scienticat** [comment]
> Hello :)
> It currently doesn't. Translating the .ENG (dialog files) in itself isn't difficult, but you will have to create a custom spritesheet for the chinese font as the default one doesn't have chinese characters. It can probably be done though, if you can provide a chinese character spritesheet where the glyphs are about the same size as the default ones

Can you tell me which file is the spritesheet file you are referring to? I have tried this 3 files: “silver\sprites\font.spr”,“silver\sprites\systfont.spr”“silver\sprites\sysfont2.spr”,but each of them seems to be incorrect。

**Comment by othias** [comment]
The font used for the dialogs is FONT.SPR, it contains all the english letters, plus some with diacritics, and a bunch of 1x1 sprites. In total there are 256 character sprites which are directly mapped to the ascii characters (for example '+' is 43 in ascii, so it is the 43rd sprite in FONT.SPR counting from zero).
So it means the game can only support up to 256 characters, and out of those you will only be able to use like 240 because some are special characters (like buttons and such).
I don't know Chinese, is 240ish characters enough for a complete translation ?

**Comment by scienticat** [comment]
> The font used for the dialogs is FONT.SPR, it contains all the english letters, plus some with diacritics, and a bunch of 1x1 sprites. In total there are 256 character sprites which are directly mapped to the ascii characters (for example '+' is 43 in ascii, so it is the 43rd sprite in FONT.SPR counting from zero).
> So it means the game can only support up to 256 characters, and out of those you will only be able to use like 240 because some are special characters (like buttons and such).
> I don't know Chinese, is 240ish characters enough for a complete translation ?

It’s a pity, that’s not enough. Chinese are a logogram，not composed of letters.For example, in English "HE",In Chinese is "他"；“SHE” in Chinese is "她","it" is "它"。Every Chinese character in the encoding is a separate encoding。I counted and organized all the translated dialogs in silver.The minimum number of Chinese characters is 1515, this does not contain punctuation and special characters。In this way, it is not a good idea to start with the eng file.

**Comment by othias** [comment]
Then I'm afraid there's no easy way do to this, at least not without further modification :( My focus is currently on extracting the assets, but if one day an engine reimplementation is done (my very long term goal), this could be a new feature.

**Comment by scienticat** [comment]
Do you have more information about silver? I checked the official Chinese version issued in China in 1999. It is true that the official Chineseization is not based on the translation of the eng file. I found Chinese font files, as well as some DLLs named after the font. So I think at least the official version of the Chinese version is to modify the main program. However, the main program in 1999 cannot run on win10, and the virtual machine of win98 cannot run because it cannot run D3D program. The Steam version should also be fixed based on the original, so I don't have much clue now. Maybe I can only try to decompile the steam version.

**Comment by othias** [comment]
I don't have the chinese version of the game so I can't say, but perhaps there is a way to make the chinese DLLs work with the GOG version? Either way, this is outside the scope of silvie for now.
